# Generated by Django 6.0.3 on 2026-04-12 14:26

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [TrigramExtension()]
